/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
#include "main.h"
#include <math.h>

void Delay(unsigned int ms);
void SystemClock_Config(void);
void Init_LED0(void);
void DAC_Channel2_Init(void);
void trigger_kick(void);
void Audio_Timer_IRQHandler(void);

#define SAMPLE_RATE 8000

volatile uint8_t kick_active = 0;

float phase = 0.0f;
float freq = 150.0f;        // starting frequency (Hz)
float amplitude = 1.0f;



int main(void)
{
    HAL_Init();
    /*SystemClock_Config();*/

    Init_LED0();
		DAC_Channel2_Init();
	
    while (1)
    {
				DAC->DHR12R2 = 4095;  // max
				HAL_Delay(500);

				DAC->DHR12R2 = 0;     // min
				HAL_Delay(500);
    }
}

void Init_LED0()
{
    uint32_t temp;
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;

    temp = GPIOA->MODER;
    temp &= ~(0x03 << (2 * 1));
    temp |= (0x01 << (2 * 1));
    GPIOA->MODER = temp;

    temp = GPIOA->OTYPER;
    temp &= ~(0x01 << 1);
    GPIOA->OTYPER = temp;

    temp = GPIOA->PUPDR;
    temp &= ~(0x03 << (2 * 1));
    GPIOA->PUPDR = temp;
}

void Delay(unsigned int n)
{
  int i;
  for (; n > 0; n--)
  for (i = 0; i < 136; i++) ;
}

void trigger_kick(void)
{
    kick_active = 1;
    phase = 0.0f;
    freq = 150.0f;     // initial pitch
    amplitude = 1.0f;  // full volume
}

void Audio_Timer_IRQHandler(void)
{
    if (kick_active)
    {
        // Generate sine wave
        float sample = amplitude * sinf(phase);

        // Convert to DAC (12-bit: 0–4095)
        uint16_t dac_val = (uint16_t)((sample + 1.0f) * 2048);
        DAC->DHR12R2 = dac_val;

        // Advance phase
        phase += 2.0f * 3.14159f * freq / SAMPLE_RATE;

        // Wrap phase
        if (phase > 2.0f * 3.14159f)
            phase -= 2.0f * 3.14159f;

        // Exponential decay (volume)
        amplitude *= 0.995f;

        // Pitch drop
        freq *= 0.9995f;

        // Stop when silent
        if (amplitude < 0.001f)
            kick_active = 0;
    }
    else
    {
        // Output silence (midpoint)
        DAC->DHR12R2 = 2048;
    }
}

/* ---------------------- CLOCK CONFIGURATION ---------------------- */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1);

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_MSI;
  RCC_OscInitStruct.MSIState = RCC_MSI_ON;
  RCC_OscInitStruct.MSICalibrationValue = 0;
  RCC_OscInitStruct.MSIClockRange = RCC_MSIRANGE_6; // 4 MHz
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
  HAL_RCC_OscConfig(&RCC_OscInitStruct);

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|
                                RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_MSI;
  RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0);
}



// This function is called whenever there is an error, such as illegal memory access
void Error_Handler(void)
{
  // We don't really need to do anything for errors, so just stay here forever
  __disable_irq();
  while (1)
  {
		
  }
}

void DAC_Channel2_Init(void) {
	
	//Enabling DAC Clock
	RCC->APB1ENR1 |= RCC_APB1ENR1_DAC1EN;
	
	//Disabling DAC
	DAC->CR &= ~( DAC_CR_EN1 | DAC_CR_EN2 );
	
	//Setting to mode 000
	DAC->MCR &= ~ (7U<<16);
	
	//Disable trigger for DAC channel 2
	DAC->CR &= ~DAC_CR_TEN2;
	
	//Enabling DAC channel 2
	DAC->CR |= DAC_CR_EN2;
	
	//Enable the clock of GPIO port A 
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	
	//Set I/O mode as analog
	GPIOA->MODER &= ~(3U << (2*5));
	GPIOA->MODER |= 3U<<(2*5);
}



// ! IMPORTANT ! All code below this line is generated by STM32CubeMX and should not be modified
#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
